version: "3.8"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  consumer:
    build:
      context: ./consumer/
      dockerfile: ./Dockerfile
    command:
      - bash
      - -c
      - |
        npm run dev:consumer
    volumes:
      - ./consumer/src/:/app/src
  producer:
    build:
      context: ./producer/
      dockerfile: ./Dockerfile
    command:
      - bash
      - -c
      - |
        npm run dev:producer
    volumes:
      - ./producer/src:/app/src